---
fixtures:
  symlinks:
    sssd: "#{source_dir}"
    auditd: "#{source_dir}/../auditd"
    augeasproviders_core: "#{source_dir}/../augeasproviders_core"
    augeasproviders_grub: "#{source_dir}/../augeasproviders_grub"
    common: "#{source_dir}/../common"
    concat: "#{source_dir}/../concat"
    nscd: "#{source_dir}/../nscd"
    openldap: "#{source_dir}/../openldap"
    pki: "#{source_dir}/../pki"
    stdlib: "#{source_dir}/../stdlib"
